name: rms_easy_payments
description: RMS Communications Easy Payments recharge app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
